### ISSUE TITLE
Three bugs in evaluation code?

### ISSUE THREAD

**Issue by lhao0301** [wangshy31/MANet_for_Video_Object_Detection#5]
There are two bugs in evaluation code???,  which also exists in  code of FGFA.
1. Case when `KEY_FRAME_INTERVAL` is 0. (single-frame baseline, all detection results are malposed (2-th frame->1-th frame).
2.  Case when the length of a video is shorter than `KEY_FRAME_INTERVAL`
@wangshy31

**Comment by lhao0301** [comment]
It seems that the runtime evaluation in function `pred_eval` is also not reasonable. Part of `feature extraction time` is ignored.

**Comment by bbidong** [comment]
@lhao0301 Hi, I study on Video_Object_Detection, may I have a talk with you ??

**Comment by lhao0301** [comment]
@bbidong Sorry, now, I don't work on VOD any more after graduation.

**Comment by bbidong** [comment]
@lhao0301  haha，thanks for your reply anyway.
